use_frameworks!

target 'CreatuLocalization_Example' do
  pod 'CreatuLocalization', :path => '../'

  target 'CreatuLocalization_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
